// QuickslingShell.idl : IDL source for QuickslingShell.exe
//

// This file will be processed by the MIDL tool to
// produce the type library (QuickslingShell.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";

[
	uuid(E914AE13-9D45-4527-BFCA-FEDCC31DC3B0),
	version(1.0),
	helpstring("QuickslingShell 1.0 Type Library")
]
library QuickslingShellLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");
	importlib("sdkevent.dll");
	[
		uuid(575D3E6F-170D-48D3-B746-A5A20A869949),
		helpstring("QBSDKCallback Class")
	]
	coclass QBSDKCallback
	{
		[default] interface IQBEventCallback;
	};
};
